[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/data/*"
  to = "https://api.staging.newstand.com/data/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auto_login"
  to = "https://api.staging.newstand.com/auto_link"
  status = 200
  force = true
